### ISSUE TITLE
Not working anymore.

### ISSUE THREAD

**Issue by akanimax** [sweta20/hotstar-linux#1]
This extension might have worked in the past. I recently stumbled upon a similar problem while accessing the premium hotstar videos on linux. It really pains a lot that the videos don't play properly on the google chrome browser for linux. So, tried your solution, but no luck. Might be good if you work it around a bit more.

**Comment by ParitoshBh** [comment]
Agreed. Wrote about it a couple of months back but it isn't working anymore.

**Comment by akanimax** [comment]
Not quite relevant; but here goes nothing. Do you know any solution that works for sure? I am not really a fan of hacky solutions, but I am worried I might run out of my subscription. LOL!

**Comment by ParitoshBh** [comment]
Well I had an extra windows license so ended up installing Windows 7 in Gnome boxes and it kind of works well! Not the most convenient solution but hey, it works ;)

**Comment by sweta20** [comment]
I have been using it still! And it works perfectly well.. Though you wont be able to access every premium videos.

**Comment by akanimax** [comment]
Not sure about that; but doesn't work on my linux (ubuntu 16.04) chrome. It moves to the hlsplayer.net site with the url copied from the hotstar video url but the video doesn't play. And, it is not just me, I know it didn't work for @ParitoshBh either (from the above issue conversation). Might reconsider looking at it again.

**Comment by sweta20** [comment]
Can you provide me the url once on which you tried?

**Comment by akanimax** [comment]
http://www.hotstar.com/movies/free-runner/1000067908/watch
try this link. When I click the hotstar plugin, it goes to this site:
https://www.hlsplayer.net/

and, in the box it shows undefined. May be you are picking some wrong value from the page in your javascript. 

Ps. sorry for the late reply. I was busy with some other work

**Comment by sweta20** [comment]
I am sorry I should have mentioned it earlier. Your url should look like 
 http://www.hotstar.com/movies/free-runner/1000067908
The id should be the last part of url.

**Comment by sweta20** [comment]
I will update the current extension in a couple of days.. I hope it will be able to solve most of the problems.
