### ISSUE TITLE
it grabs the url but does not play

### ISSUE THREAD

**Issue by anpr22** [sweta20/hotstar-linux#2]
the hotstar-linux extension grabs url in m3u8 player but play button does not seem to work. the screen remains blank in chrome.

Thanks

**Comment by sweta20** [comment]
Check for flash plugin. It should be allowed for the website to work.

**Comment by anpr22** [comment]
It is allowed . please tell me any other way to play hotstar on Linux mint

**Comment by sweta20** [comment]
Did you allowed it explicitly for the website.  If yes, and it still didn't work, will update the plugin in a couple of days. Till that time, follow:
https://askubuntu.com/questions/778906/problem-playing-hotstar-videos

<img width="1534" alt="screen shot 2017-07-05 at 8 32 26 pm" src="https://user-images.githubusercontent.com/11375341/27870718-4140889e-61c1-11e7-962c-348f0be3c60c.png">

**Comment by anpr22** [comment]
Wow, thanks a lot. After explicitly allowing it is streaming like a charm.
You are genius .

I have upsc mains else will watch later for sure
