### ISSUE TITLE
Not working for premium videos

### ISSUE THREAD

**Issue by nagabharat** [sweta20/hotstar-linux#3]
This is not working for premium videos.

**Comment by sweta20** [comment]
Which premium videos are you using it for?

**Comment by SiddhantMeshram** [comment]
Yes, videos which are free are working perfectly. But videos which require premium membership access are not working. For eg. Game of Thrones episodes.

**Comment by sweta20** [comment]
It doesn't work for HBO premium. Needs to be modified but you can definitely watch sports premium videos.

**Comment by ecthiender** [comment]
Hi, The plugin is not working for Silicon Valley (premium show). Can you point me to what I can modify to watch these videos? I'll be happy to contribute.
